export const STRINGS = {
  palette: {
    placeholder: 'Search for apps and commands…',
    searchHint: 'Search for apps and commands…',
    filterPlaceholder: 'Type to filter entries…',
    back: 'Back',
    close: 'Close',
    empty: 'No results found. Try a different search.',
    clipboardEmpty: 'Clipboard history is empty. Copy something to see it here.',
    quickActions: 'Quick Actions',
    applications: 'Applications',
    system: 'System',
    footerNavigate: '↑↓ Navigate',
    footerOpen: '↵ Open',
    footerDashboard: '⌘+J Dashboard',
    esc: 'ESC',
    openApplications: 'Open Applications...',
    clipboardHistory: 'Clipboard History',
    clearAll: 'Clear all',
    actionPanel: 'Actions',
    actionPanelHint: 'Ctrl+K Actions',
    loading: 'Loading...',
    searching: 'Searching...',
    actionPaste: 'Paste / Copy',
    actionPin: 'Pin',
    actionUnpin: 'Unpin',
    actionFavorite: 'Favorite',
    actionUnfavorite: 'Unfavorite',
    actionDelete: 'Delete',
    actionClearHistory: 'Clear History',
    startSuggestions: 'Suggestions',
    calculator: 'Calculator',
    snippets: 'Snippets',
    dashboard: 'Dashboard',
    settings: 'Settings',
    lockScreen: 'Lock Screen',
    sleep: 'Sleep',
    emptyTrash: 'Empty Trash',
    results: 'Results',
    suggestions: 'Suggestions',
    commands: 'Commands',
    preferences: 'Preferences',
    openCommand: 'Open Command',
    actions: 'Actions',
    categoryApplication: 'Application',
    categorySystem: 'System',
    categoryFile: 'File',
    categoryClipboard: 'Clipboard',
    categorySnippet: 'Snippet',
    categoryCalculator: 'Calculator',
    useQueryWith: 'Use "{{query}}" with…',
    webSearchGoogle: 'Google Search',
    webSearchDuckDuckGo: 'DuckDuckGo Search',
    webSearchBing: 'Bing Search',
    webSearches: 'Web Searches',
    calculatorExpression: 'Expression',
    calculatorResult: 'Result',
    copyAnswer: 'Copy Answer',
  },
  errors: {
    rootNotFound: 'Root element not found',
    unexpected: 'An unexpected error occurred',
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Try again',
  },
} as const
